apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: pvc
              mountPath: /data/db
          env:
            - name: MONGO_CONN_STR
              value: "mongodb://admin:password@mongodb-0.mongodb,mongodb-1.mongodb,mongodb-2.mongodb:27017/langdb"
            - name: MONGO_USERNAME
              value: admin
            - name: MONGO_PASSWORD
              value: password

  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
