apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: voting-lang-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
      name: frontend
    